name: GitHub Actions Runner in Docker - Release
on:
  push:
    tags:
      - '*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  ubuntu_latest_tag:
    runs-on: ubuntu-latest

    needs: create-release
    steps:
      - name: Copy Repo Files
        uses: actions/checkout@master
      - name: get version
        run: echo 'TAG='${GITHUB_REF#refs/tags/} >> $GITHUB_ENV
      - name: Get GitHub organization or user
        run: echo 'ORG='$(dirname ${GITHUB_REPOSITORY}) >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
      - name: Build
        uses: nick-invision/retry@v2
        with:
          max_attempts: 3
          retry_on: error
          timeout_minutes: 120
          command: docker buildx build -f Dockerfile -t ${ORG}/ghar-node:${TAG} --output "type=image,push=true" --platform linux/amd64,linux/arm64 .
